# inventories/lab/group_vars/routers.yml
# ============================
ntp_server: 10.10.10.1            # dùng chung cho tất cả router
backup_dir: "{{ playbook_dir }}/../backups/{{ inventory_hostname }}"
backup_root: "/tmp/router_backups"

