# inventories/lab/group_vars/routers.yml
# ======================================

# 1. Định danh & kết nối Cisco
ansible_network_os: cisco.ios.ios
ansible_connection: ansible.netcommon.network_cli
ansible_become: true
ansible_become_method: enable

# 2. Đường dẫn chuẩn
golden_dir:  "{{ playbook_dir }}/../golden"
running_dir: "{{ playbook_dir }}/../running"
diff_dir:    "{{ playbook_dir }}/../diff"
backup_root: "{{ playbook_dir }}/../backups"

# 3. Các mẫu dòng bỏ qua khi diff
ignore_lines:
  - '^!Time'
  - '^uptime is'
  - '^ntp clock-period'
  - '^license udi'
  - '^crypto key generate'

# 4. Thông số chung cho toàn mạng
ntp_server: 10.10.10.1

