all:
  children:
    routers:
      hosts:
        R3:
          ansible_host: 192.168.45.138
          ansible_user: netadmin
          ansible_password: AnsibleRocks!
          ansible_network_os: cisco.ios.ios
          ansible_become: yes
          ansible_become_method: enable
          ansible_connection: ansible.netcommon.network_cli
