all:
  children:
    routers:
      hosts:
        R3:
          ansible_host: 192.168.45.138          # IP thật của R3 trên Cloud
          ansible_user: netadmin
          ansible_password: AnsibleRocks!
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
          ansible_ssh_common_args: '-o KexAlgorithms=+diffie-hellman-group-exchange-sha1 -o HostKeyAlgorithms=+ssh-rsa -o Ciphers=+aes128-cbc'

        R2:
          ansible_host: 192.168.45.138          # IP ngoài cùng (R3)
          ansible_port: 2022                   # NAT R3 ➜ R2:22
          ansible_user: netadmin
          ansible_password: AnsibleRocks!
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
          ansible_ssh_common_args: >
            -oKexAlgorithms=+diffie-hellman-group14-sha1
            -oHostKeyAlgorithms=+ssh-rsa

