all:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: admin
    ansible_password: "cisco123"
    ansible_become_method: enable
    ansible_become_password: "cisco123"

    # Giữ đúng SSH args yếu như host bạn đã chạy được
    ansible_ssh_common_args: "-o KexAlgorithms=+diffie-hellman-group-exchange-sha1 -o HostKeyAlgorithms=+ssh-rsa -o Ciphers=+aes128-cbc -o StrictHostKeyChecking=no"

    # WAN hiện tại của R-W (đổi nếu khác)
    rw_wan_ip: 192.168.45.141

  children:
    routers:
      hosts:
        R1:
          ansible_host: "{{ rw_wan_ip }}"
          ansible_port: 22111   # <— nếu bạn NAT 22xxx, mở comment và điền đúng
        R2:
          ansible_host: "{{ rw_wan_ip }}"
          ansible_port: 22112
        RW:
          ansible_host: "{{ rw_wan_ip }}"
          ansible_port: 22
