---
- name: Get show version from routers
  hosts: routers
  gather_facts: false # Not needed for network devices for this task

  tasks:
    - name: Execute 'show version' command
      cisco.ios.ios_command:
        commands:
          - show version
      register: router_output # Store the output in a variable

    - name: Print the output
      debug:
        var: router_output.stdout_lines[0] # Display the first line of output
